language: ruby
env:
  matrix:
  - RACK_ENV=development
sudo: false
rvm:
- 2.3.1
services:
- docker
before_install:
- ./bin/pull_worker.sh
deploy:
  provider: rubygems
  api_key:
    secure: cpjPZRBul+mdYxIPGZrz0P+dhjX3NJDbe5nNNDw6DAoysfSGKLF2GbYY/7A5gaaBUUHSFtMDQbTcQFHvC3Vsl2UIuGbCh8vDhtJjLk+FjralXJtwxzyd7Z9UA2oMKBhsERdTlwnD/uxp72Ab/rh5wr1ZvfqBe+PpgGLccMkF6Owojqa0Gm2C2LV4TJ+Y2Q8ME73zYxBQlWgMnDaH8o1fVXcwcVKDdHlmgK2TmS8i4huDDT21I0VxRIm6VUf6A4+wdHKAcfv5rvpkOLRLEnDN40iBqrkmrHUbFjDpkMblcn20fR3/ljBZrMIq1z9YY5bN5QVVfp32jE9ZXBbS4jQUuhH6n3C1oWWUEBzgjo3rNwiiEEeNrFsT3Qfq4XdHV+NLOefYkVaVl3GIjld/39FoPxxE21CApaAUCkFR/u3K2ffK8S3kBVsa43LunAijMTzQWG+xcwCYF+TqShLoW+ldR9qrOwfi+MtSTC2/0BWd7/S+8/w/g4zZo8xjndEdTmcmQ6fkqTau2QFYmeSHyEuGhnaFEIaw2SZOENCudeGIkg4A4g7b6KhqiPpLxeb7wtT1pgyELs2YPVzUXT4LF78L1BVJC+fcj6MewTESo1B6aMZTccLKlP+2kRV0dbzrfEwrVBuG1h4Sy3FPmX6F2Gc0fA6WLcCrc4IQTjHxsDIn5E0=
  gem: mumuki-php-runner
  on:
    tags: true
    repo: mumuki/mumuki-php-runner
